#!/usr/bin/env bash
# A Bash script that lists all running processes with exact STARTED time and hierarchy

ps -eo user,lstart,cmd --forest | awk 'NR==1 { $2="STARTED"; $3=""; $4=""; $5=""; $6=""; print $1, $2, $7 } NR>1 { printf "%s %s %s %s %s %s ", $1, $2, $3, $4, $5, $6; for (i=7;i<=NF;++i) printf "%s ", $i; print "" }'

