#!/usr/bin/env bash
# This script prints special messages for 4th and 8th iterations using if-elif-else

i=1
while [ $i -le 20 ]
do
echo "$i"
case $i in
 echo "bad luck from China"
 ;;
 echo "bad luck from Japan"
;;
echo "bad luck from Italy"
;;
esac
i=$((i + 1))
done
